### ISSUE TITLE
Error: `The schema must be one of the following: public, storage, graphql_public` 

### ISSUE THREAD

**Issue by devkiran** [supaboard/app#1]
I'm trying to setup app locally but getting this following error.

```
{
  userAccounts: null,
  error: {
  code: 'PGRST106',
  details: null,
  hint: null,
  message: 'The schema must be one of the following: public, storage, graphql_public'
}
```

**Comment by benmann** [comment]
Ah yes! Sorry we lack a ton of documentation at this point. This is likely because we're using a schema called `supaboard` and you need to allow access to it through the Supabase API, in the Supabase settings as shown below.
Will add a how to run locally / install guide soon 🙏

![screenshot](https://github.com/supaboard/app/assets/7561396/378c934e-b5b0-4eb5-b53e-3a73ca599165)

**Comment by devkiran** [comment]
Thanks, it worked.
